### ISSUE TITLE
Reference images

### ISSUE THREAD

**Issue by Geocali** [johnmarcc/OpenCV_BanquePostale_AccountStatement#1]
Hello

Could you upload your reference images ?
They are not the same in visual and in headless mode, as I can see from the following code ?

```python
    # load Reference image for the current password digit
    if (param_HEADLESS_PROCESS == "True"):
        referenceDIR = 'REF_HEADLESS'
    else:
        referenceDIR = 'REF_LIVE_MODE'

    referenceImage = 'img/'+referenceDIR+'/'+listPWD[element]+'_REF.png'
```

**Comment by jeanmarcc** [comment]
Hello,

Sorry for the delay (I didn't get any notifs from github)

If your inquiry is still current, I put the pics there: 

[REF_HEADLESS.zip](https://github.com/johnmarcc/OpenCV_BanquePostale_AccountStatement/files/6728309/REF_HEADLESS.zip)
[REF_LIVE_MODE.zip](https://github.com/johnmarcc/OpenCV_BanquePostale_AccountStatement/files/6728310/REF_LIVE_MODE.zip)


---------------------- in french --------------
Je pense que ce script fonctionne toujours car le clavier virtuel de la Banque Postale n'a pas change depuis plus de 2 ans.
